name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1  # Replace with your AWS region
  ECR_REPOSITORY: vars3.0-test-repo  # Replace with your ECR repository name
  VERSION: 3.0.${{ github.run_number }}
  Task_Definition: VARS3-0-Test-Task
  Cluster: VARS3-0-Test-Cluster
  Service: VARS3-0-Test-Service
  account_id: 366115556563
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: VARS3.0

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        
      run: |
        TIMESTAMP=$(date +'%Y.%m.%d.%H.%M')
        
        # Build the Docker image
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION .
        # Tag the image as latest
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION $ECR_REGISTRY/$ECR_REPOSITORY:$TIMESTAMP
        # Push the image to ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TIMESTAMP
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION
        
        
  deploy:
      runs-on: ubuntu-latest
      environment: VARS3.0
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
  
      - name: Get current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ env.Task_Definition }} \
            --query taskDefinition \
            > task-definition.json
  
      - name: Update image in task definition
        env:
          IMAGE: arn:aws:ecr:${{ env.AWS_REGION }}:$account_id:repository/${{ env.ECR_REPOSITORY }}:$VERSION

        run: |
          echo "Latest ECR image ARN : $IMAGE"
          cat task-definition.json | \
          jq --arg IMAGE "$IMAGE" \
          '.containerDefinitions[0].image=$IMAGE |
          del(.taskDefinitionArn,.revision,.status,.requiresAttributes,.compatibilities,.registeredAt,.registeredBy)' \
          > new-task-definition.json
  
      - name: Register new task definition
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-task-definition.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
  
          echo "TaskDefinition: $TASK_DEF_ARN "
  
      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster ${{ env.Cluster }} \
            --service ${{ env.Service }} \
            --task-definition $TASK_DEF_ARN
  
      - name: Wait for deployment
        run: |
          aws ecs wait services-stable \
            --cluster ${{ env.Cluster }} \
            --service ${{ env.Service }} 
  
      - name: Deployment successful
        run: echo "ECS deployment completed successfully 🚀"
