name: Build React Frontend

on:
  push:
    branches: [ "UI" ]

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Dist Folder
        run: npm run build

      # This is the step you requested
      - name: List generated files
        run: ls -R dist/
