name: Teams notification
on:
  workflow_dispatch:
    inputs:
      Version:
        description: 'Please Mention Version here '
        required: true
        type: string
        
jobs:
  teams:  
    runs-on: ubuntu-22.04

    steps:
      - name: Notify Teams
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{secrets.TEAMS_WEBHOOK_URL}}
          message: "Hello, The changes got updates woth v - ${{github.event.inputs.Version}} "
          title: "Manual Notification"
          
